/*
 * This file is generated by jOOQ.
*/
package jooq.db;


import javax.annotation.Generated;

import jooq.db.tables.Author;
import jooq.db.tables.Book;
import jooq.db.tables.BookStore;
import jooq.db.tables.BookToBookStore;
import jooq.db.tables.Language;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHOR_PKEY = Indexes0.AUTHOR_PKEY;
    public static final Index BOOK_PKEY = Indexes0.BOOK_PKEY;
    public static final Index BOOK_STORE_NAME_KEY = Indexes0.BOOK_STORE_NAME_KEY;
    public static final Index BOOK_TO_BOOK_STORE_PKEY = Indexes0.BOOK_TO_BOOK_STORE_PKEY;
    public static final Index LANGUAGE_PKEY = Indexes0.LANGUAGE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index AUTHOR_PKEY = createIndex("author_pkey", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index BOOK_PKEY = createIndex("book_pkey", Book.BOOK, new OrderField[] { Book.BOOK.ID }, true);
        public static Index BOOK_STORE_NAME_KEY = createIndex("book_store_name_key", BookStore.BOOK_STORE, new OrderField[] { BookStore.BOOK_STORE.NAME }, true);
        public static Index BOOK_TO_BOOK_STORE_PKEY = createIndex("book_to_book_store_pkey", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.NAME, BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, true);
        public static Index LANGUAGE_PKEY = createIndex("language_pkey", Language.LANGUAGE, new OrderField[] { Language.LANGUAGE.ID }, true);
    }
}
