/*
 * This file is generated by jOOQ.
*/
package jooq.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.author_id_seq</code>
     */
    public static final Sequence<Integer> AUTHOR_ID_SEQ = new SequenceImpl<Integer>("author_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.book_id_seq</code>
     */
    public static final Sequence<Integer> BOOK_ID_SEQ = new SequenceImpl<Integer>("book_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.language_id_seq</code>
     */
    public static final Sequence<Integer> LANGUAGE_ID_SEQ = new SequenceImpl<Integer>("language_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
