/*
 * This file is generated by jOOQ.
*/
package jooq.db;


import javax.annotation.Generated;

import jooq.db.tables.Author;
import jooq.db.tables.Book;
import jooq.db.tables.BookStore;
import jooq.db.tables.BookToBookStore;
import jooq.db.tables.Language;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.author</code>.
     */
    public static final Author AUTHOR = jooq.db.tables.Author.AUTHOR;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = jooq.db.tables.Book.BOOK;

    /**
     * The table <code>public.book_store</code>.
     */
    public static final BookStore BOOK_STORE = jooq.db.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>public.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = jooq.db.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>public.language</code>.
     */
    public static final Language LANGUAGE = jooq.db.tables.Language.LANGUAGE;
}
