/*
 * This file is generated by jOOQ.
*/
package jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = -1190192070;

    private final Integer id;
    private final Integer authorId;
    private final String  title;
    private final Integer publishedIn;
    private final Integer languageId;

    public Book(Book value) {
        this.id = value.id;
        this.authorId = value.authorId;
        this.title = value.title;
        this.publishedIn = value.publishedIn;
        this.languageId = value.languageId;
    }

    public Book(
        Integer id,
        Integer authorId,
        String  title,
        Integer publishedIn,
        Integer languageId
    ) {
        this.id = id;
        this.authorId = authorId;
        this.title = title;
        this.publishedIn = publishedIn;
        this.languageId = languageId;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public String getTitle() {
        return this.title;
    }

    public Integer getPublishedIn() {
        return this.publishedIn;
    }

    public Integer getLanguageId() {
        return this.languageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(title);
        sb.append(", ").append(publishedIn);
        sb.append(", ").append(languageId);

        sb.append(")");
        return sb.toString();
    }
}
