/*
 * This file is generated by jOOQ.
*/
package jooq.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStore implements Serializable {

    private static final long serialVersionUID = -1581751287;

    private final String  name;
    private final Integer bookId;
    private final Integer stock;

    public BookToBookStore(BookToBookStore value) {
        this.name = value.name;
        this.bookId = value.bookId;
        this.stock = value.stock;
    }

    public BookToBookStore(
        String  name,
        Integer bookId,
        Integer stock
    ) {
        this.name = name;
        this.bookId = bookId;
        this.stock = stock;
    }

    public String getName() {
        return this.name;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public Integer getStock() {
        return this.stock;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookToBookStore (");

        sb.append(name);
        sb.append(", ").append(bookId);
        sb.append(", ").append(stock);

        sb.append(")");
        return sb.toString();
    }
}
